log_dir: "Models/LJSpeech"
first_stage_path: "first_stage.pth"
save_freq: 1
log_interval: 50
device: "cuda"
epochs_1st: 6 # number of epochs for first stage training (pre-training)
epochs_2nd: 5 # number of epochs for second stage training (joint training)
batch_size: 2
grad_accum: 1
ga_max: 3
ga_min: 1
ga_start_high_pct: 100.0
ga_free_low_pct: 25.0
ga_free_high_pct: 35.0
ga_grow_patience: 3
ga_grow_cooldown: 5
fm_max_chunks: 64
max_len: 1000 # maximum number of frames (10 seconds), 1000 = 12.5 s For second stage due to lack of memory forced to use 400, want 1000
#pretrained_model: ""  # for First stage
pretrained_model: "Models/LJSpeech/first_stage.pth"
second_stage_load_pretrained: false # set to true if the pre-trained model is for 2nd stage
load_only_params: false # set to true if do not want to load epoch numbers and optimizer parameters
decoder_channels_last: true
adv_max_samples: 96000   # 24000 = ~1.0s @ 24kHz ; 96000 = ~4.0s @ 24kHz (diminishing returns post this)

F0_path: "Utils/JDC/bst.t7"
ASR_config: "Utils/ASR/config.yml"
ASR_path: "Utils/ASR/epoch_00080.pth"
PLBERT_dir: 'Utils/PLBERT/'

precision:
  mode: fp32        # one of: fp32 | bf16 | fp16
  use_autocast: false        # if false → force full-fp32, no AMP
  validate_in_fp32: true    # run validation strictly in fp32 even if training mixed
  tf32: false                # allow TF32 for matmuls when in fp32 mode

data_params:
  train_data: "Data/train_list.txt"
  val_data: "Data/val_list.txt"
  root_path: "Data/LJSpeech-1.1/wavs"
  OOD_data: "Data/OOD_texts.txt"
  mel_cache_dir: "Data/mel_cache"
  min_length: 10 # sample until texts with this size are obtained for OOD texts

preprocess_params:
  sr: 24000
  spect_params:
    n_fft: 2048
    win_length: 1200
    hop_length: 300

model_params:
  multispeaker: false

  dim_in: 64 
  hidden_dim: 512
  max_conv_dim: 512
  n_layer: 3
  n_mels: 80

  n_token: 178 # number of phoneme tokens
  max_dur: 50 # maximum duration of a single phoneme
  style_dim: 128 # style vector size
  
  dropout: 0.2

  # config for decoder
  decoder: 
      type: 'istftnet' # either hifigan or istftnet
      resblock_kernel_sizes: [3,7,11]
      upsample_rates :  [10, 6]
      upsample_initial_channel: 512
      resblock_dilation_sizes: [[1,3,5], [1,3,5], [1,3,5]]
      upsample_kernel_sizes: [20, 12]
      gen_istft_n_fft: 20
      gen_istft_hop_size: 5
      
  # speech language model config
  slm:
      model: 'microsoft/wavlm-base-plus'
      sr: 16000 # sampling rate of SLM
      hidden: 768 # hidden size of SLM
      nlayers: 13 # number of layers of SLM
      initial_channel: 64 # initial channels of SLM discriminator head
  
  # style diffusion model config
  diffusion:
    embedding_mask_proba: 0.1
    # transformer config
    transformer:
      num_layers: 3
      num_heads: 8
      head_features: 64
      multiplier: 2

    # diffusion distribution config
    dist:
      sigma_data: 0.2 # placeholder for estimate_sigma_data set to false
      estimate_sigma_data: true # estimate sigma_data from the current batch if set to true
      mean: -3.0
      std: 1.0
  
loss_params:
    lambda_mel: 5. # mel reconstruction loss
    lambda_gen: 1. # generator loss
    lambda_slm: 1. # slm feature matching loss
    
    lambda_mono: 1. # monotonic alignment loss (1st stage, TMA)
    lambda_s2s: 1. # sequence-to-sequence loss (1st stage, TMA)
    TMA_epoch: 1 # TMA starting epoch (1st stage)

    lambda_F0: 1. # F0 reconstruction loss (2nd stage)
    lambda_norm: 1. # norm reconstruction loss (2nd stage)
    lambda_dur: 1. # duration loss (2nd stage)
    lambda_ce: 20. # duration predictor probability output CE loss (2nd stage)
    lambda_sty: 1. # style reconstruction loss (2nd stage)
    lambda_diff: 1. # score matching loss (2nd stage)
    
    diff_epoch: 1 # style diffusion starting epoch (2nd stage)
    joint_epoch: 3 # joint training starting epoch (2nd stage)

optimizer_params:
  lr: 0.0001 # general learning rate
  bert_lr: 0.00001 # learning rate for PLBERT
  ft_lr: 0.00001 # learning rate for acoustic modules
  # impl: torch          # baseline PyTorch AdamW (current)
  # impl: bnb8bit      # A) 8-bit AdamW on GPU
  impl: bnb_paged8   # B) Paged 8-bit AdamW (offload-ish)
  
slmadv_params:
  min_len: 400 # minimum length of samples
  max_len: 500 # maximum length of samples
  batch_percentage: 0.5 # to prevent out of memory, only use half of the original batch size
  iter: 10 # update the discriminator every this iterations of generator update
  thresh: 5 # gradient norm above which the gradient is scaled
  scale: 0.01 # gradient scaling factor for predictors from SLM discriminators
  sig: 1.5 # sigma for differentiable duration modeling

ema:
  enable: true
  decay: 0.999
  modules: ["decoder","style_encoder","predictor","predictor_encoder"]
  start_epoch: 0
  eval: true
  update_freq: 1